[build]
  publish = "dist/public"
  command = "npm install --legacy-peer-deps && npm run build:client:npx"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist/public" 